// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssqvtfpinejogstzodu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3F2dGZwaW5lam9nc3R6b2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzcxNDIsImV4cCI6MjA2MTYxMzE0Mn0.7oF5RFS2cIezw6OL511fKuQNtQHL1Qk4ZvQMw9aUse0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);